[build]
  command = "npm run build"
  publish = "dist"

# API proxy (cubre /api y /api/*)
[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbywvwt7ceQAN-q9F7y5g4QQ1i7znUk85-UsYJxszUZNKoqg9KSBSDBv6VWXv2RaP-pE/exec"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbywvwt7ceQAN-q9F7y5g4QQ1i7znUk85-UsYJxszUZNKoqg9KSBSDBv6VWXv2RaP-pE/exec"
  status = 200
  force = true

# SPA fallback (SIEMPRE al final)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
